// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqfjadlbmdwlenfrvjfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZmphZGxibWR3bGVuZnJ2amZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMzM2MDQsImV4cCI6MjA3NTkwOTYwNH0.spu6-O8UKnfFEDz8Wm3Ds3Be-mFt3X1lFoHMcAqgFUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});